[package]
name = "whirled"
version = "0.1.0"
authors = ["Daniel Doran <ddoran3@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.9.0"
byteorder = "1.4.3"
env_logger = "0.8.4"
imgui = "0.7.0"
imgui-wgpu = "0.15.1"
imgui-winit-support = { version = "0.7.1", default-features = false, features = ["winit-25"] }
log = "0.4.14"
glam = "0.16.0"
raw-window-handle = "0.3.3"
wgpu = "0.8.1"
winit = "0.25.0"
shaders = { path = "./shaders" }
