[package]
name = "compile_shaders"
version = "0.1.0"
authors = ["Daniel Doran <ddoran3@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
shaderc = "0.7.2"
proc-macro2 = "1.0.26"
syn = "1.0.70"
quote = "1.0.9"
